# Generated by Django 5.1.7 on 2025-03-19 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='vendedor',
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.DeleteModel(
            name='MetodoPago',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
