# Generated by Django 5.1.7 on 2025-03-24 00:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_producto_estado'),
        ('ventas', '0004_alter_metodopago_options_metodopago_fecha_creacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='lote_vendido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='inventario.inventarioproducto'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='total_descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modificacion_ventas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_ventas', to=settings.AUTH_USER_MODEL),
        ),
    ]
