# Generated by Django 5.1.7 on 2025-03-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_detalleventa_lote_vendido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='turno',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='usuario_modificacion',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='usuario_registro',
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.DeleteModel(
            name='MetodoPago',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
