# Generated by Django 5.1.7 on 2025-03-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_alter_detalleventa_options_alter_metodopago_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='referencia_externa',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
