# Generated by Django 5.1.7 on 2025-03-19 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reporte',
        ),
    ]
