# Generated by Django 5.1.7 on 2025-04-03 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reportes', '0002_delete_reporte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('cajas_general', 'Reporte de Cajas General'), ('cortes_historial', 'Historial de Cortes de Cajas'), ('ventas_historial', 'Historial de Ventas'), ('inventario', 'Reporte de Inventario'), ('proveedores', 'Reporte de Proveedores')], max_length=30)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('parametros', models.TextField(blank=True, help_text='Parámetros utilizados en la generación del reporte (ej. rango de fechas).', null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de reporte',
                'verbose_name_plural': 'Logs de reportes',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
