# Generated by Django 5.1.7 on 2025-03-23 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='archivo_corte_pdf',
            new_name='archivo_corte',
        ),
    ]
