# Generated by Django 5.1.7 on 2025-03-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_rename_archivo_corte_pdf_turno_archivo_corte'),
        ('ventas', '0006_remove_venta_metodo_pago_remove_venta_turno_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Turno',
        ),
    ]
