# Generated by Django 5.1.7 on 2025-03-25 02:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import turnos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turnos', '0003_delete_turno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_fin_estimada', models.DateTimeField()),
                ('hora_fin_real', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, help_text='Monto en efectivo con el que inició el turno', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('monto_total_efectivo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monto_total_tarjeta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monto_total_transferencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monto_total_cheque', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado')], default='activo', max_length=10)),
                ('pdf_reporte', models.FileField(blank=True, null=True, upload_to=turnos.models.ruta_pdf_corte)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
