# Generated by Django 5.1.7 on 2025-03-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='total_cambios_dados',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Suma total de los cambios entregados en ventas en efectivo', max_digits=10),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora_fin_estimada',
            field=models.DateTimeField(verbose_name='Hora de fin estimada'),
        ),
    ]
