# Generated by Django 5.1.7 on 2025-03-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_turno_total_cambios_dados_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
    ]
