# Generated by Django 5.1.7 on 2025-03-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0006_alter_turno_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='cerrado_automaticamente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turno',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Notas internas del turno', null=True),
        ),
    ]
