# Generated by Django 5.1.7 on 2025-03-17 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descuento_porcentaje',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_caducidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id_proveedor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_venta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_minimo',
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InventarioProducto',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('descuento_porcentaje', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.producto')),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modificacion_stock', to=settings.AUTH_USER_MODEL)),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_stock', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
