# Generated by Django 5.1.7 on 2025-03-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_fecha_modificacion_producto_stock_minimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
