# Generated by Django 5.1.7 on 2025-03-19 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_producto_codigo_barras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioproducto',
            name='id_proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_proveedor', to='inventario.proveedor'),
        ),
        migrations.AlterField(
            model_name='inventarioproducto',
            name='lote',
            field=models.CharField(default='SIN-LOTE', max_length=50),
            preserve_default=False,
        ),
    ]
