# Generated by Django 5.1.7 on 2025-03-19 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_metodopago_remove_producto_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='id_metodo_pago',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id_usuario',
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.DeleteModel(
            name='MetodoPago',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
