# Generated by Django 5.1.7 on 2025-03-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_producto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioproducto',
            name='codigo_lote',
            field=models.CharField(default='LOTE-UNICO', max_length=30, unique=True),
        ),
    ]
