# Generated by Django 5.1.7 on 2025-04-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_alter_inventarioproducto_codigo_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioproducto',
            name='lote',
            field=models.CharField(default='', max_length=50),
        ),
    ]
