# Generated by Django 5.1.7 on 2025-03-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='user',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor')], default='vendedor', max_length=20),
        ),
    ]
